package com.example.triviaapp.customClasses;

import java.io.Serializable;

public class Game implements Serializable {
    protected boolean isCompetitive;
    protected Subject subject;
    protected Question[] questions;
    protected int timePerQuestionSec;

    protected int numberOfQuestions = 0;
    protected boolean isAutoGenerated;

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        isAutoGenerated = autoGenerated;
    }

    public int getTimePerQuestionSec() {
        return timePerQuestionSec;
    }

    public void setTimePerQuestionSec(int timePerQuestionSec) {
        this.timePerQuestionSec = timePerQuestionSec;
    }

    public boolean isCompetitive() {
        return isCompetitive;
    }

    public void setCompetitive(boolean competitive) {
        isCompetitive = competitive;
    }

    public Subject getSubject() {
        return subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    public Question[] getQuestions() {
        return questions;
    }

    public void setNumberOfQuestions(int numberOfQuestions) {
        this.numberOfQuestions = numberOfQuestions;
    }

    public void setQuestions(Question[] questions) {
        this.questions = questions;
        if(!isAutoGenerated){
            this.numberOfQuestions = this.questions.length;
        }
    }

    public int getNumberOfQuestions() {
        return numberOfQuestions;
    }

    public static final String DEFAULT_SUBJECT = "capitals";
    public static final int DEFAULT_QUESTION_NUMBER = 2;
    public static final int DEFAULT_TIME_PER_QUESTION_SEC = 5;

    public static final int COMPETITIVE_QUESTION_NUMBER = 4;
    public static final int COMPETITIVE_TIME_PER_QUESTION_SEC = 5;

    public Game() {
        this.subject = new Subject();
        this.isCompetitive = false;
        this.questions = null;
        this.timePerQuestionSec = Game.DEFAULT_TIME_PER_QUESTION_SEC;
    }

    public Game(Game game){
        this.subject = game.subject;
        this.isCompetitive = game.isCompetitive;
        this.questions = game.questions;
        this.numberOfQuestions = game.numberOfQuestions;
        this.timePerQuestionSec = game.timePerQuestionSec;
    }

}
